### ISSUE TITLE
Config Links has an 404 error

### ISSUE THREAD

**Issue by woehrer12** [PaskLab/cardano-docker#38]
https://github.com/PaskLab/cardano-docker/blob/a1a0a78eef29c9b8f8a37ff8db960eafc07e6303/README.md?plain=1#L156-L159

**Comment by pascallapointe** [comment]
Yes that part of the documentation as been outdated for a longtime. I'll take time to review and update the whole thing later this week since you opened that issue.

In the mean time, you can fetch the current official environment files here:
[https://book.play.dev.cardano.org/env-mainnet.html](https://book.play.dev.cardano.org/env-mainnet.html)

Please note that the current setup use naming convention for some config files, which might differ slightly from the downloaded files name. I'll make all that customizable through the docker-compose.yaml while reviewing the docs.

**Comment by pascallapointe** [comment]
Documentation updated with current environment files location.
Closing the issue.
